[version]
path = "src/pointers/__init__.py"

[envs.default]
dependencies = [
  "ward",
  "typing_extensions",
]
[envs.default.scripts]
tests = "ward --path tests/"

[envs.docs]
dependencies = [
  "mkdocs",
  "mkdocstrings[python]",
]
[envs.docs.scripts]
build = "mkdocs build --clean"
serve = "mkdocs serve --dev-addr localhost:8000"

[build.targets.wheel]
packages = ["src/pointers"]
include = ["src/pointers/*.py", "src/pointers/_pointers.pyi"]

#[build.hooks.custom]
#enable-by-default = true
